### ISSUE TITLE
References in the text

### ISSUE THREAD

**Issue by iyeldinov** [mgrankin/ru_transformers#6]
Input: _Захотелось выпить_
Output: 
>  _Захотелось выпить_ и понять. Э.  По: Шаг 1. Перевод Виктора Пелевина. СПб.: Азбука, 2014. С. 17.].) Гегель тоже вспоминает, что наблюдатель в положении сидя способен видеть вещи определенным образом и оставаться при этом вне их видимости.

**Comment by mgrankin** [comment]
That's not really a bug, since the dataset contains such references. But, I understand that it is an undesired artifact. There are several ways to deal with it. The simplest is to provide more context as an input so the model will understand this is not a reference. Alternatively you can filter generated references during the process of generation or cleanup the dataset and fine-tune the model on the clean data.
